# Generated by Django 5.2.3 on 2025-07-16 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Curso',
        ),
    ]
