# Generated by Django 5.2.3 on 2025-08-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0003_alumno_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='password',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
