# Generated by Django 5.2.3 on 2025-08-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0004_docente_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='docente',
            name='cursos',
            field=models.ManyToManyField(related_name='docentes', to='General.curso'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='docente',
            name='password',
            field=models.CharField(default='123456', max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='rfc',
            field=models.CharField(max_length=13),
        ),
    ]
