# Generated by Django 5.2.3 on 2025-08-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0005_remove_docente_especialidad_docente_cursos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='alumnos', to='General.curso'),
        ),
    ]
