# Generated by Django 5.2.3 on 2025-08-05 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0007_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_entrega',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
